### ISSUE TITLE
DB correction

### ISSUE THREAD

**Issue by nabat** [vintoniak/perl_work#9]
CREATE TABLE `image_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image` blob NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=big5;

1. Better use primary for auto_increment
2. auto_increment must be unsigned
3. dont use double index definition
    PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
4. use correct charset

**Comment by vintoniak** [comment]
done
